import { getProductsAPI } from "@/api/Product";
import Product from "@/components/Product";
import Head from "next/head";
import Image from "next/image";

export const getStaticProps = async () => {
  const response = await getProductsAPI();
  const products = response.data;

  if (products.length === 0) {
    return {
      props: {
        products: [],
      },
    };
  }

  return {
    props: {
      products,
    },
  };
};

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Broco Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-1 gap-2 p-4">
        {products.map((product) => (
          <Product product={product.attributes} key={product.id} />
        ))}
      </main>
    </>
  );
}
